/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskCategory = IDL.Variant({
  'Healthcare' : IDL.Null,
  'Insurance' : IDL.Null,
  'Bills' : IDL.Null,
  'Documents' : IDL.Null,
  'Other' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'category' : TaskCategory,
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, TaskCategory],
      [IDL.Nat],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getMyUpcomingTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'toggleTaskStatus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, TaskCategory],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskCategory = IDL.Variant({
    'Healthcare' : IDL.Null,
    'Insurance' : IDL.Null,
    'Bills' : IDL.Null,
    'Documents' : IDL.Null,
    'Other' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'category' : TaskCategory,
  });
  
  return IDL.Service({
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, TaskCategory],
        [IDL.Nat],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getMyUpcomingTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'toggleTaskStatus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, TaskCategory],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };