/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'title' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'dueDate' : bigint,
  'description' : string,
  'category' : TaskCategory,
}
export type TaskCategory = { 'Healthcare' : null } |
  { 'Insurance' : null } |
  { 'Bills' : null } |
  { 'Documents' : null } |
  { 'Other' : null };
export type TaskStatus = { 'Completed' : null } |
  { 'Pending' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'createTask' : ActorMethod<[string, string, bigint, TaskCategory], bigint>,
  'deleteTask' : ActorMethod<[bigint], boolean>,
  'getMyTasks' : ActorMethod<[], Array<Task>>,
  'getMyUpcomingTasks' : ActorMethod<[], Array<Task>>,
  'toggleTaskStatus' : ActorMethod<[bigint], boolean>,
  'updateTask' : ActorMethod<
    [bigint, string, string, bigint, TaskCategory],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];