/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface Task {
    id: bigint;
    status: TaskStatus;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    dueDate: bigint;
    description: string;
    category: TaskCategory;
}
export enum TaskCategory {
    Healthcare = "Healthcare",
    Insurance = "Insurance",
    Bills = "Bills",
    Documents = "Documents",
    Other = "Other"
}
export enum TaskStatus {
    Completed = "Completed",
    Pending = "Pending"
}
export interface backendInterface {
    createTask(title: string, description: string, dueDate: bigint, category: TaskCategory): Promise<bigint>;
    deleteTask(id: bigint): Promise<boolean>;
    getMyTasks(): Promise<Array<Task>>;
    getMyUpcomingTasks(): Promise<Array<Task>>;
    toggleTaskStatus(id: bigint): Promise<boolean>;
    updateTask(id: bigint, title: string, description: string, dueDate: bigint, category: TaskCategory): Promise<boolean>;
}
import type { Task as _Task, TaskCategory as _TaskCategory, TaskStatus as _TaskStatus, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createTask(arg0: string, arg1: string, arg2: bigint, arg3: TaskCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_TaskCategory_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_TaskCategory_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getMyTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTasks();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTasks();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUpcomingTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUpcomingTasks();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUpcomingTasks();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleTaskStatus(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskStatus(arg0);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: TaskCategory): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_TaskCategory_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_TaskCategory_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_TaskCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskCategory): TaskCategory {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    title: string;
    userId: _UserId;
    createdAt: _Timestamp;
    dueDate: bigint;
    description: string;
    category: _TaskCategory;
}): {
    id: bigint;
    status: TaskStatus;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    dueDate: bigint;
    description: string;
    category: TaskCategory;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n6(_uploadFile, _downloadFile, value.status),
        title: value.title,
        userId: value.userId,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        category: from_candid_TaskCategory_n8(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Completed: null;
} | {
    Pending: null;
}): TaskStatus {
    return "Completed" in value ? TaskStatus.Completed : "Pending" in value ? TaskStatus.Pending : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Healthcare: null;
} | {
    Insurance: null;
} | {
    Bills: null;
} | {
    Documents: null;
} | {
    Other: null;
}): TaskCategory {
    return "Healthcare" in value ? TaskCategory.Healthcare : "Insurance" in value ? TaskCategory.Insurance : "Bills" in value ? TaskCategory.Bills : "Documents" in value ? TaskCategory.Documents : "Other" in value ? TaskCategory.Other : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n4(_uploadFile, _downloadFile, x));
}
function to_candid_TaskCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskCategory): _TaskCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskCategory): {
    Healthcare: null;
} | {
    Insurance: null;
} | {
    Bills: null;
} | {
    Documents: null;
} | {
    Other: null;
} {
    return value == TaskCategory.Healthcare ? {
        Healthcare: null
    } : value == TaskCategory.Insurance ? {
        Insurance: null
    } : value == TaskCategory.Bills ? {
        Bills: null
    } : value == TaskCategory.Documents ? {
        Documents: null
    } : value == TaskCategory.Other ? {
        Other: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
